// Public-domain and MIT-licensed quotations from Catholic saints, doctors,
// popes, and writers, used to replace the text of censored posts when the
// option is enabled. Expanded from the catholic-readings-api dataset (MIT).
(function initCatholicQuotes(root) {
  const quotes = [
    { text: "You have made us for yourself, O Lord, and our heart is restless until it rests in you.", author: "St. Augustine" },
    { text: "Late have I loved you, O Beauty ever ancient, ever new.", author: "St. Augustine" },
    { text: "To one who has faith, no explanation is necessary. To one without faith, no explanation is possible.", author: "St. Thomas Aquinas" },
    { text: "Without the Way, there is no going; without the Truth, there is no knowing; without the Life, there is no living.", author: "Thomas Ã  Kempis" },
    { text: "At the Day of Judgement we shall not be asked what we have read, but what we have done.", author: "Thomas Ã  Kempis" },
    { text: "Have patience with all things, but first of all with yourself.", author: "St. Francis de Sales" },
    { text: "Let nothing disturb you, let nothing frighten you. All things pass away: God never changes. God alone suffices.", author: "St. Teresa of Ãvila" },
    { text: "In the evening of life, we will be judged on love alone.", author: "St. John of the Cross" },
    { text: "Be who God meant you to be and you will set the world on fire.", author: "St. Catherine of Siena" },
    { text: "Start by doing what is necessary; then do what is possible; and suddenly you are doing the impossible.", author: "St. Francis of Assisi" },
    { text: "Act as if everything depended on you; trust as if everything depended on God.", author: "St. Ignatius of Loyola" },
    { text: "Ignorance of Scripture is ignorance of Christ.", author: "St. Jerome" },
    { text: "No one heals himself by wounding another.", author: "St. Ambrose" },
    { text: "Prayer is the place of refuge for every worry, a foundation for cheerfulness.", author: "St. John Chrysostom" },
    { text: "The proof of love is in the works.", author: "Pope St. Gregory the Great" },
    { text: "Ora et labora â€” pray and work.", author: "St. Benedict" },
    { text: "The glory of God is man fully alive.", author: "St. Irenaeus" },
    { text: "Miss no single opportunity of making some small sacrifice, here by a smiling look, there by a kindly word.", author: "St. ThÃ©rÃ¨se of Lisieux" },
    { text: "Pray, hope, and donâ€™t worry.", author: "St. Padre Pio" },
    { text: "The Christian ideal has not been tried and found wanting. It has been found difficult; and left untried.", author: "G. K. Chesterton" },
    { text: "Prayer is the inner bath of love into which the soul plunges itself.", author: "St. John Vianney" },
    { text: "I believe in order to understand; and I understand, the better to believe.", author: "St. Anselm" },
    { text: "Christian, remember your dignity.", author: "Pope St. Leo the Great" },
    { text: "Charity is that with which no man is lost, and without which no man is saved.", author: "St. Robert Bellarmine" },
    { text: "When someone steals another's clothes, we call them a thief. Should we not give the same name to one who could clothe the naked and does not?", author: "Saints Basil the Great and Gregory Nazianzen" },
    { text: "Look then on Jesus, the Author and Preserver of faith: in complete sinlessness He suffered.", author: "St. Raymond of Penyafort" },
    { text: "The chief service I owe you, O God, is that every thought and word of mine should speak of you.", author: "St. Hilary of Poitiers" },
    { text: "The devil is afraid of us when we pray and make sacrifices. He is also afraid when we are humble and good.", author: "St. Anthony of Egypt" },
    { text: "We must remember that we are not to seek our own will, but the will of God.", author: "St. Fabian" },
    { text: "Christ made my soul beautiful with the jewels of grace and virtue. I belong to Him whom the angels serve.", author: "St. Agnes" },
    { text: "The most powerful weapon to conquer the devil is humility.", author: "St. Vincent" },
    { text: "Nothing is so strong as gentleness, nothing so gentle as real strength.", author: "St. Francis de Sales" },
    { text: "Let no one despise your youth, but be an example to the believers in word, in conduct, in love, in spirit, in faith, in purity.", author: "Saints Timothy and Titus" },
    { text: "Do something. Get moving. Be confident. Risk new things. Stick with it. Get on your knees. Then be ready for big surprises.", author: "St. Angela Merici" },
    { text: "To one who has faith, no explanation is necessary.", author: "St. Thomas Aquinas" },
    { text: "Run, jump, shout, but do not sin.", author: "St. John Bosco" },
    { text: "O Lord, deliver us from all evil of body and soul.", author: "St. Blase" },
    { text: "Jesus Christ, Lord of all, you see my heart, you know my desires; possess all that I am, you alone.", author: "St. Agatha" },
    { text: "My religion teaches me to pardon my enemies and all who have offended me.", author: "St. Paul Miki and Companions" },
    { text: "I asked you and you would not listen, so I asked my God and He did listen.", author: "St. Scholastica" },
    { text: "I am ready with joy to die for the Christian faith.", author: "St. Cyril" },
    { text: "He does not love Christ who does not love the cross of Christ.", author: "St. Peter Damian" },
    { text: "We worship the Creator of the universe, and we affirm that Jesus Christ is His Son.", author: "St. Polycarp" },
    { text: "I prefer to be found pure before God rather than stained with the riches of the world.", author: "St. Casimir" },
    { text: "I cannot be called by any other name than what I amâ€”a Christian.", author: "Saints Perpetua and Felicity" },
    { text: "A married woman must leave her devotions at the altar to find God in her household affairs.", author: "St. Frances of Rome" },
    { text: "Christ beside me, Christ before me, Christ behind me, Christ within me.", author: "St. Patrick" },
    { text: "The cross has ransomed the world; it has driven away the shadows and restored the light.", author: "St. Cyril of Jerusalem" },
    { text: "Time is not our own, and we must give a strict account of it.", author: "St. Turibius of Mogrovejo" },
    { text: "I fear not exile or death; I fear only failing the truth.", author: "St. Martin I" },
    { text: "I believe in order to understand.", author: "St. Anselm of Canterbury" },
    { text: "Go into all the world and preach the gospel to every creature.", author: "St. Mark the Evangelist" },
    { text: "God does not ask of you mere ordinary virtue. He demands downright perfection!", author: "St. Pius V" },
    { text: "Work was the daily expression of love in the life of the Family of Nazareth.", author: "St. Joseph the Worker" },
    { text: "The Son of God became man so that we might become God.", author: "St. Athanasius" },
    { text: "The peace of Christ in the kingdom of Christ.", author: "St. John I" },
    { text: "The name of Jesus is a glory for the preacher, because of the shining splendor of that name.", author: "St. Bernardine of Siena" },
    { text: "I am innocent and I die innocent. I forgive with all my heart those responsible for my death.", author: "St. Christopher Magallanes and Companions" },
    { text: "I am not afraid to die. It is to close the eyes to the world and open them to God.", author: "St. Rita of Cascia" },
    { text: "A joyful heart is more easily made perfect than a downcast one.", author: "St. Philip Neri" },
    { text: "He who sings prays twice.", author: "St. Augustine of Canterbury" },
    { text: "If you have too much to do, with God's help you will find time to do it all.", author: "Saints Marcellinus and Peter" },
    { text: "A Christian who is convinced that his life is in the hands of God has no reason to fear.", author: "Saints Charles Lwanga and Companions" },
    { text: "A talkative, over-curious person is like an oven which is open and exposed on all sides.", author: "St. Norbert" },
    { text: "Virtue is the beauty of the soul.", author: "St. Ephrem" },
    { text: "Pray as though everything depended on God. Work as though everything depended on you.", author: "St. Barnabas the Apostle" },
    { text: "Sit in your cell as in paradise. Put the whole world behind you and forget it.", author: "St. Romuald" },
    { text: "O Lord, let me not be troubled for gold and silver, for where all my treasure is Thou knowest.", author: "St. Paulinus of Nola" },
    { text: "Mary, mother of God, who held the Uncontainable in your womb.", author: "St. Cyril of Alexandria" },
    { text: "You are the Christ, the Son of the living God.", author: "Saints Peter and Paul" },
    { text: "My Lord and my God!", author: "St. Thomas the Apostle" },
    { text: "The only reason God raised me to the throne was that I should have means to assist the needy.", author: "St. Elizabeth of Portugal" },
    { text: "Mary, the Mother of God, is our Mother also.", author: "Saints Augustine Zhao Rong" },
    { text: "Prayer and work. (Ora et labora)", author: "St. Benedict of Nursia" },
    { text: "The sick are our lords and masters.", author: "St. Camillus de Lellis" },
    { text: "The best way to know God is to love Him.", author: "St. Bonaventure" },
    { text: "I believe in Jesus Christ, the Son of the living God.", author: "St. Apollinaris" },
    { text: "All for the honor and glory of God.", author: "St. Lawrence of Brindisi" },
    { text: "I have seen the Lord!", author: "St. Mary Magdalene" },
    { text: "How could I bear a crown of gold when the Lord bears a crown of thorns?", author: "St. Bridget of Sweden" },
    { text: "God is found in silence and solitude.", author: "St. Charbel Makhlouf" },
    { text: "My life is for the service of the Gospel.", author: "St. James" },
    { text: "Yes, Lord. I have come to believe that you are the Christ, the Son of God.", author: "St. Martha" },
    { text: "Fasting is the soul of prayer, almsgiving is the lifeblood of fasting.", author: "St. Peter Chrysologus" },
    { text: "Lord, teach me to be generous. Teach me to serve you as you deserve.", author: "St. Ignatius of Loyola" },
    { text: "He who trusts himself is lost. He who trusts God can do all things.", author: "St. Alphonsus Maria de Liguori" },
    { text: "My God, if my tongue cannot say in every moment that I love You, I want my heart to repeat it at every breath.", author: "St. Jean Vianney" },
    { text: "Arm yourself with prayer rather than a sword; wear humility rather than fine clothes.", author: "St. Dominic" },
    { text: "The treasures of the Church are the poor.", author: "St. Lawrence of Rome" },
    { text: "We become what we love and who we love shapes what we become.", author: "St. Clare" },
    { text: "Faithfully do what God expects of you each moment, and leave the rest up to Him.", author: "St. Jane Frances de Chantal" },
    { text: "The Lord is our strength and our shield.", author: "Saints Pontian" },
    { text: "No one in the world can change Truth. What we can do and should do is to seek truth and to serve it when we have found it.", author: "St. Maximilian Mary Kolbe" },
    { text: "Our wish, our object, our chief preoccupation must be to form Jesus in ourselves.", author: "St. John Eudes" },
    { text: "The measure of loving God is to love Him without measure.", author: "St. Bernard of Clairvaux" },
    { text: "Holy Communion is the shortest and safest way to Heaven.", author: "St. Pius X" },
    { text: "Rabbi, you are the Son of God; you are the King of Israel.", author: "St. Bartholomew the Apostle" },
    { text: "I would rather see you dead at my feet than that you should ever commit a mortal sin.", author: "St. Louis/Saint Joseph of Calasanz" },
    { text: "Nothing is far from God.", author: "St. Monica" },
    { text: "Thou hast made us for thyself, O Lord, and our heart is restless until it finds its rest in thee.", author: "St. Augustine of Hippo" },
    { text: "Learn of the Heart of God in the Words of God.", author: "St. Gregory the Great" },
    { text: "We must speak to them with our hands by giving, before we try to speak to them with our lips.", author: "St. Peter Claver" },
    { text: "Let us relieve burdens and afflictions by mutual love.", author: "Saints Cornelius" },
    { text: "Whoever finds God, finds everything; whoever loses God, loses everything.", author: "St. Robert Bellarmine" },
    { text: "My power is nothing but there is a God in heaven who can resist you.", author: "St. Januarius" },
    { text: "Pray, hope, and don't worry. Worry is useless.", author: "St. Pio of Pietrelcina" },
    { text: "Bless the Lord, all you his angels, mighty in power, who do his bidding.", author: "Saints Michael" },
    { text: "Ignorance of the Scriptures is ignorance of Christ.", author: "St. Jerome" },
    { text: "I will spend my heaven doing good on earth.", author: "St. Therese of the Child Jesus" },
    { text: "O Bonitas! O Goodness!", author: "St. Bruno" },
    { text: "To live is Christ, to die is gain.", author: "St. Denis and Companions Martyrs/Saint John Leonardi" },
    { text: "If offences abound, then, let mercy also abound.", author: "St. Callistus I" },
    { text: "Let nothing disturb you, let nothing frighten you. God alone suffices.", author: "St. Teresa of Jesus" },
    { text: "The greater one is by birth, the greater one must be in virtue.", author: "St. Hedwig" },
    { text: "Wherever the bishop appears, there let the people be.", author: "St. Ignatius of Antioch" },
    { text: "The greater our cross, the greater is our gain.", author: "Saints Jean de Brebeuf and Isaac Jogues" },
    { text: "Be not afraid! Open wide the doors for Christ!", author: "Pope Saint John Paul II" },
    { text: "Those who are called to the table of the Lord must glow with the brightness that comes from the good example.", author: "St. John of Capistrano" },
    { text: "To serve Christ is to reign.", author: "Saints Simon and Jude" },
    { text: "Everything, even sweeping... could be a prayer, if it were offered to God.", author: "St. Martin de Porres" },
    { text: "Be sure that you first preach by the way you live.", author: "St. Charles Borromeo" },
    { text: "Christian, recognize your dignity and, now that you share in Godâ€™s own nature, do not return to your former base condition by sinning.", author: "St. Leo the Great" },
    { text: "Lord, if your people still need me, I do not draw back from the labor. Your will be done.", author: "St. Martin of Tours" },
    { text: "I am ready to die for the holy union.", author: "St. Josaphat" },
    { text: "My children, love and fear God; for they who fear God, have not to fear death.", author: "St. Margaret of Scotland/Saint Gertrude the Great" },
    { text: "Let us fix our eyes on the blood of Christ and understand how precious it is to His Father.", author: "St. Clement I" },
    { text: "The blood of martyrs is the seed of Christians.", author: "St. Andrew Dung-Lac and Companions" },
    { text: "If you are ruled by the mind you are king, if by the body you are a slave.", author: "St. Catherine of Alexandria" },
    { text: "We have found the Messiah.", author: "St. Andrew the Apostle" },
    { text: "Give me the children until they are seven, and anyone may have them afterward.", author: "St. Francis Xavier" },
    { text: "The icon is a mirror, a window to the divine.", author: "St. John Damascene" },
    { text: "Where the Church is, there is no death, but life eternal.", author: "St. Ambrose" },
    { text: "Am I not here, who am your Mother?", author: "St. Juan Diego Cuauhtlatoatzin" },
    { text: "I, Damasus, have dedicated these verses to the honor of the martyrs.", author: "St. Damasus I" },
    { text: "Fight all error, but do it with good humor, patience, kindness, and love.", author: "St. John of Kenty" },
    { text: "Lord Jesus, receive my spirit.", author: "St. Stephen" },
    { text: "Timothy left to me only the heritage of his faith and courage.", author: "St. Sylvester I" },
  ];
  if (typeof module === 'object' && module.exports) module.exports = quotes;
  root.TabCloserQuotes = quotes;
})(typeof globalThis !== 'undefined' ? globalThis : this);
